language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --pylint --cov

branches:
  only:
    - main
    - development
    - calc-v1
    - calc-v2
    - calc-v3
    - calc-v4
    - calc-v5
    - calc-v6